# Generated by Django 3.2 on 2021-09-30 20:01

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hoods.hood'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='users',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1631717620/default_uomrne.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.hood')),
            ],
            options={
                'verbose_name_plural': 'Police',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='health', max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.hood')),
            ],
            options={
                'verbose_name_plural': 'Health',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_mail', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.users')),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoods.hood')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
